# Generated by Django 5.2.3 on 2025-06-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_options_alter_customuser_avatar_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="token",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Token"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="country",
            field=models.CharField(
                blank=True, max_length=25, null=True, verbose_name="Страна"
            ),
        ),
    ]
