# Generated by Django 5.2.2 on 2025-06-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="created_at",
        ),
        migrations.AddField(
            model_name="article",
            name="create_at",
            field=models.DateField(
                auto_now_add=True, null=True, verbose_name="Дата создания"
            ),
        ),
    ]
