# Generated by Django 5.2.2 on 2025-06-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_remove_article_created_at_article_create_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="create_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
