# Generated by Django 5.2.2 on 2025-06-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_article_create_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="active_is",
            field=models.BooleanField(verbose_name="Признак публикации"),
        ),
    ]
