# Generated by Django 5.2.3 on 2025-06-17 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_article_active_is"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ["views_counter"],
                "permissions": [("can_unpublish_article", "Can unpublish article")],
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
            },
        ),
    ]
