# Generated by Django 5.2.3 on 2025-06-17 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_article_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ["author", "views_counter"],
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
            },
        ),
    ]
