# Generated by Django 5.2.3 on 2025-06-18 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_alter_article_author"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Author",
        ),
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ["views_counter"],
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
            },
        ),
        migrations.RemoveField(
            model_name="article",
            name="author",
        ),
    ]
