# Generated by Django 5.2.3 on 2025-06-19 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0014_article_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="owner",
        ),
    ]
